### ISSUE TITLE
重复加锁

### ISSUE THREAD

**Issue by DreamSaddle** [TaXueWWL/redis-distributed-lock#19]
你好，使用AOP在加锁日志中会发现有重复加锁的现象。

[这里是你的代码](https://github.com/TaXueWWL/redis-distributed-lock/blob/89a8e99c411468775e0d89af13013dafd87f7d9f/redis-distributed-lock-core/src/main/java/com/snowalker/handler/RedisLockHandler.java#L35)

就是首次执行目标方法时会执行一次`around`方法，当调用`joinPoint.proceed();`时又会执行一次。我想请教一下这是什么原因呢？

**Comment by einsitang** [comment]
`joinPoint.proceed() ` 不就是运行资源执行逻辑么，怎么会再次 `执行加锁动作`？
